### ISSUE TITLE
Condition text on Token's HUD

### ISSUE THREAD

**Issue by elemorelli** [Dorako/pf2e-dorako-ux#1]
The module [Monk's Little Details](https://github.com/ironmonk88/monks-little-details) adds a setting to display the conditions' names on the token's HUD. This works as it is for PF2e and helps to find conditions without memorizing icons or having to search through all the conditions for the obscure ones.

Example:

![image](https://github.com/Dorako/pf2e-dorako-ux/assets/1661552/6e1260cb-ebc8-496e-a2bc-8637721ab6e0)

I believe this would be a nice UX improvement (And will allow me to uninstall that module 😄 )

**Comment by Dorako** [comment]
I think MLD's implementation works well, and you'll notice it's already supported by Dorako UI.
As long as MLD is maintained (which I have no reason to believe is changing anytime soon) I think it does its job.
