### ISSUE TITLE
"Minimize hotbar" option shifts UI up

### ISSUE THREAD

**Issue by Calvin263** [Dorako/pf2e-dorako-ux#16]
FVTT Build 315 Version 11 Stable
Pf2e: 5.13.6
Dorako UX: 1.3.2

Steps to reproduce:
1. Go to any tab.
2. Click on "Chat Messages" tab.

![image](https://github.com/Dorako/pf2e-dorako-ux/assets/10062913/64a7303b-e3b3-4f60-bf36-e5cf692a89d3)

**Comment by Calvin263** [comment]
Also, have the "Minimize hotbar" option enabled.

**Comment by Dorako** [comment]
I've removed the code for this feature, might bring it back at some point, but there's enough stuff that happens related to hotbars that it might not be worthwhile.
