### ISSUE TITLE
[Bug] "Failed drawing interface canvas group: This is not a registered game setting"

### ISSUE THREAD

**Issue by Vogliadicone** [Dorako/pf2e-dorako-ux#20]
After updating to PF2 Doraka UX 1.3.4 I wanted to add some actors to a scene. After dragging the actors from the sidebar to the map, the token didn't show up. When I try to reload the map, I get the message:
![Unbenannt](https://github.com/Dorako/pf2e-dorako-ux/assets/119852651/f1c5f054-b4a8-43ee-823d-033f52ca9bbb)
The console shows this:
![Screenshot 2024-03-11 171524](https://github.com/Dorako/pf2e-dorako-ux/assets/119852651/add04b6a-f6f2-49bc-8905-316b2b6c3417)
I then have to disable PF" Doraka UX to load the map and be able to delete the token.

This happens only with some tokens, but I haven't been able to figure out, which one are affected. It happens for sure with an actor that is shaken. If the actor is unshaken, I can add him to the map. The moment I make him shaken, I get the error message from above in the console. If I try to add this actur now to a scene, he didn't appear and a reload of the scene isn't possible.
![Screenshot 2024-03-11 172312](https://github.com/Dorako/pf2e-dorako-ux/assets/119852651/b077cae5-e68e-490e-b677-0f615a7827a2)
Let me know, if you need more data.

- Foundry VTT: 11.315
- Swade System: 3.3.4
- PF2 Doraka UX 1.3.4
- PF2 Doraka UI 3.0.6 (can't use the newer ones, because I need the legacy styling for SWADE)
- Browser: Google Chrome

**Comment by Dorako** [comment]
Thanks for the report, seems like some system-specific code snuck into the last patch. I'll put out a new patch that fixes that, let me know if something still appears wrong - I'm not familiar enough with SWADE to be able to tell whether anything is wrong myself.

**Comment by Dorako** [comment]
1.3.5 out now

**Comment by Vogliadicone** [comment]
It got ab bit better with 1.3.5, but not everything is solved. So right now, I can apply the shaken status to an actor on the map without problems. But I still can't drag an actor with the shaken status on the map:
![Screenshot 2024-03-11 174220](https://github.com/Dorako/pf2e-dorako-ux/assets/119852651/3801f5cf-e1a1-4952-9675-7707ed188663)

**Comment by Dorako** [comment]
Can you try exporting the actor and attaching it here?

**Comment by Vogliadicone** [comment]
Shure, there you go, here's a shaken actor:
[fvtt-Actor-pegame-UKxgVb7PCy0gm5F1.json](https://github.com/Dorako/pf2e-dorako-ux/files/14562307/fvtt-Actor-pegame-UKxgVb7PCy0gm5F1.json)

**Comment by Dorako** [comment]
Thanks, I'll have a look at some point. For now I'd recommend you just roll back to yesterday's update and lock it - if you're using SWADE I doubt you'd be missing much.

**Comment by Vogliadicone** [comment]
Thanks, I did that. Needed to go back to 1.3.2. With 1.3.3 I had the same problem with the actor statuses.
