### ISSUE TITLE
Players don't have the same settings as GM

### ISSUE THREAD

**Issue by yjeroen** [Dorako/pf2e-dorako-ux#22]
I understand the wish for players to also customize their UI.

However, could you by default have a (newly added) player start out with the same settings as the GM?

**Comment by yjeroen** [comment]
From testing these settings are set via cookie instead of Foundry setting? Can that be improved?

**Comment by Dorako** [comment]
You'll have to raise that issue with Foundry. The settings are totally normal Foundry settings, which means that client settings are local to the browser, and world settings affect everything.
There are modules that allow GM's to synchronize settings to their players, or lock certain options.

**Comment by yjeroen** [comment]
I looked into modules like that (Force Client Settings) and Dorako UX settings don't show up there.

I think you do a settings.register with the scope:'client', in that case it's saved in the localStorage? You can also register settings  with scope:'world', then it's saved to the database.
 https://foundryvtt.wiki/en/development/api/settings

**Comment by Dorako** [comment]
Yes, that is how client settings work.
A world setting is the same for the entire world, which means that it is impossible for players to change the setting at all. Only GM's can set world settings.
I use Module Management+ to set settings myself, there's also a module from Ironmonk that does a similar thing.

**Comment by yjeroen** [comment]
> Only GM's can set world settings.

Ah yes I see, my mistake. I really thought Foundry had an option for db-saved user settings. :) 

> Module Management+

What a wonderful module! Thank you for the tip.
