### ISSUE TITLE
Horizontal Rules does not work in journals using the Core Rulebook (light) Sheet theme

### ISSUE THREAD

**Issue by GillardMullek** [Dorako/pf2e-dorako-ux#24]
In  **Foundry v11.315** with **Pafhinder 2e v5.15.0 system**, all the **Horizontal Rules** had disappeared from all journals when using the **Core Rulebook (light) Sheet theme**. Horizontal Rules do not appear when we try to add them again, just a blank space appearing in their place.
![image](https://github.com/Dorako/pf2e-dorako-ux/assets/166623751/e1942e9c-9b13-445e-8a6f-aff86190706b)
![image](https://github.com/Dorako/pf2e-dorako-ux/assets/166623751/7a1918a5-08b7-4303-8c78-5158546ce4e8)
Using the PF2e Dorako UX v1.3.6 and UI - PF2e Dorako UI v3.4.7.

**Comment by Dorako** [comment]
UX has no theme settings, this is only related to UI.
