### ISSUE TITLE
Sidebar Navigation Size

### ISSUE THREAD

**Issue by pinkflumph** [Dorako/pf2e-dorako-ux#3]
Hi! It would be great to have a setting to adjust the size of the sidebar navigation buttons, similar to the setting for tools and navigation:
![image](https://github.com/Dorako/pf2e-dorako-ui/assets/99619418/22d6f1ab-5c6e-4056-b206-9a3f2dacd7ed)

The buttons are small enough in the standard Foundry layout, and even smaller with the module, especially on large screens

**Comment by Dorako** [comment]
Should be doable. The main problem I guess is running out of sidebar space, and with a variable-width sidebar you can just adjust as you want.
![CleanShot 2023-11-24 at 01 58 24@2x](https://github.com/Dorako/pf2e-dorako-ux/assets/1561190/eedc8433-1273-4cc7-acb1-66da0069e6f8)

**Comment by pinkflumph** [comment]
Thanks! Even simply increasing the height would helpful and wouldn't create the width issue, although it wouldn't look quite as elegant. The outcome on the screenshot actually looks pretty good if the extra width doesn't break anything

**Comment by Dorako** [comment]
Included in 1.1.0
