### ISSUE TITLE
UX Console error when ending combat with Carousel Combat Tracker

### ISSUE THREAD

**Issue by ottyn** [Dorako/pf2e-dorako-ux#32]
When using Carousel Combat Tracker and ending a combat, I get the following error message in the console.  The "caused by" line is referencing the compact-ui.js file of UX.

Carousel Combat Tracker: 3.0.5
Dorako UI: 3.5.11
Dorako UX: 1.4.3
Foundry: 12.330
PF2e: 6.2.0

![image](https://github.com/user-attachments/assets/78cfcbf0-5260-4226-bec2-06354742b011)

**Comment by Dorako** [comment]
Should be fixed now
