### ISSUE TITLE
PF2e v6.3.0 breaks chat avatars

### ISSUE THREAD

**Issue by keneth-dev** [Dorako/pf2e-dorako-ux#35]
The new release of the PF2e system has added avatars and player labels by default, which doesn't mesh well with Dorako features. It would be great if we could get an update since I still use other module features.

**Comment by Dorako** [comment]
Supe is investigating the best way to circumvent the system additions.
For now the best solution is to disable avatars and player tags in Dorako UX.

**Comment by Dorako** [comment]
I introduced a hack that should fix this issue.

**Comment by keneth-dev** [comment]
Works like a charm. Thank you.
