### ISSUE TITLE
Cursor vanishes when hovered over the chat textbox

### ISSUE THREAD

**Issue by bogga** [Dorako/pf2e-dorako-ux#37]
In my browser, when hovering over the chat textbox, the cursor completely vanishes. Is this intended? If so, can I turn that off?

Tested this in firefox 130.0 and chrome 128.0.6613.120, foundry 12.331, Dorako UX 1.5.2

**Comment by Dorako** [comment]
Doesn't happen on my machine, and I never seen anybody else report it.
Perhaps your text-entry cursor is simple very thin and hard to see? 

The css cursor is set to 'text' by the standard textarea element, and is not modified by UX.

**Comment by bogga** [comment]
yeah no apologies you're right, it's a combination of thin cursor and back background behind the box 🙃
