### ISSUE TITLE
Using System Fallback Makes Chat Messages Taller Compared to Normal System Behavior

### ISSUE THREAD

**Issue by Ghostdesu** [Dorako/pf2e-dorako-ux#39]
# Description

Using Dorako UX with the System Fallback portrait option selected results in unnaturally tall messages with a lot of empty space. Ideally, using the system fallback should not alter the dimension of the chat message.

# Environment
- Firefox 130.0 
- Foundry 12.331
- PF2e 6.3.1
- Module Management+ 2.2.3 (The issue persists without it but I didn't want to disable it again to take screenshots)
- Dorako UX 1.5.3

# Screenshots

Settings: 
![image](https://github.com/user-attachments/assets/1bf9462a-6d9c-4a4a-8ee1-eabfd482355e)

With no modules:
![image](https://github.com/user-attachments/assets/ea06eaac-30f3-4502-b868-917a53dc4c8f)

With Dorako UX enabled:
![image](https://github.com/user-attachments/assets/8725d63c-4bf0-4513-bb69-4420eedb7460)

**Comment by Dorako** [comment]
The system fallback setting is basically just there for if I get hit by a bus - is there a particular reason you're using it currently?
Once the system avatars approach parity with the avatars provided by UX I'll probably remove the UX ones and just rely on this system ones, but I'm not going to support two different avatar implementations.
