### ISSUE TITLE
Uncaught Error in Radial Condition HUD

### ISSUE THREAD

**Issue by janouna** [Dorako/pf2e-dorako-ux#8]
I get an uncaught exception when adding tokens to a scene, or when refreshing a scene with tokens in it. In the former case the tokens don't load, and in the latter the entire scene won't load.
```
radial-condition-hud.js:93 Uncaught (in promise) TypeError: appTheme.includes is not a function
    at drawBG (radial-condition-hud.js:93:16)
    at radial-condition-hud.js:153:7
    at Array.forEach (<anonymous>)
    at updateEffectScales (radial-condition-hud.js:143:17)
    at Token._refreshEffects (radial-condition-hud.js:171:7)
    at TokenPF2e.drawEffects (foundry.js:55424:10)
    at async TokenPF2e.drawEffects (pf2e.mjs:1350:92211)
    at async TokenPF2e._draw (foundry.js:54993:5)
    at async foundry.js:28515:7
```
I can reproduce this error with all modules except Dorako UX disabled. The error goes away if I uncheck the `Adjust token effects HUD?` setting. I'm on v315 of Foundry and v1.2.1 of Dorako UX

**Comment by Dorako** [comment]
What version of Dorako UI, assuming you are using that as well?

**Comment by janouna** [comment]
Dorako UI v3.3.5, but I have that module disabled as everything I like is in the UX module

**Comment by Dorako** [comment]
Gotcha, the check is probably looking for whether UI is installed, but not for whether it is active, will check when I get home.

**Comment by Dorako** [comment]
Now that I'm home, it looks like I've already fixed this issue locally, just haven't pushed an update including it yet. Fixed for next release.
