### ISSUE TITLE
Updated chat messages don't keep their header after refreshing the page

### ISSUE THREAD

**Issue by K4rakara** [Dorako/pf2e-dorako-ux#9]
[Video demonstration](https://github.com/Dorako/pf2e-dorako-ui/assets/40474474/b3dfe204-0f15-4ab0-9fa2-0c7bbad082bb)

In this screencast, I'm using my own chat enhancement module, which I haven't released yet, but I've also been able to reproduce it with `df-chat-enhance`.

List of enabled modules:
- Chat Commander
- DF Chat Enhancements
- libWrapper
- PF2e Dorako UI
- PF2e Dorako UX

**Comment by Dorako** [comment]
I'm not entirely sure what I'm looking at here - how does it look like if you actually type a message with "test" as the speaker? The thing that seems inconsistent to me is the avatar getting added in the first place.

**Comment by K4rakara** [comment]
Typing with test as the speaker adds the characters icon, which is just the default at the moment. Is it not supposed to add the default icon?
![Screencast from 2024-01-05 19-37-31.webm](https://github.com/Dorako/pf2e-dorako-ux/assets/40474474/c057b455-30bd-47e1-8c25-83b66d5057d3)

**Comment by Dorako** [comment]
Considering you've made your own module, I think it'll probably be easier for you to debug it.
Are there any errors in the console?
Try setting breakpoints in message-hooks.js in Dorako UX and see if you can figure out why the Avatar renders when you update it, but not when you refresh. 
You might also want to explore the pf2e-dorako-ux message flags, perhaps the avatars are not defined in the original message, and as such the code that adds the actual image is skipped.

**Comment by K4rakara** [comment]
Looks like [these lines](https://github.com/Dorako/pf2e-dorako-ux/blob/93cd865a31c4d72417a5e057a84f2da25c3209c0/esmodules/message-hooks.js#L88-L97) are the reason this happens. When updating a message, it doesn't update the tokenWasHidden flag, but calls the function that adds the avatars.

**Comment by K4rakara** [comment]
I'll be looking into this over the weekend, I'll let you know if I figure out.

**Comment by K4rakara** [comment]
I'm fairly certain that this is being caused by using `.updateSource` instead of `.update` in `addAvatarsToFlags` -- `.updateSource` only applies to the local version of the message, whereas `.update` actually sends the changes to the backend. Perhaps a second argument could be added to `addAvatarsToFlags` that would determine whether `.updateSource` or `.update` is used.

I'll do some testing locally, if I'm able to make a fix, I'll fork the repo and make a PR.

**Comment by Dorako** [comment]
Thanks, included for next release
